### ISSUE TITLE
Image Assets are missing

### ISSUE THREAD

**Issue by stardev24** [Mariii123/heli-shooter#1]
Hi,

  I have observed the code base. Some image files like cloud.png,loon.png were not uploaded,Can you please  upload the image files?

Thanks

**Comment by bittner** [comment]
Correct, I can confirm. The following files are missing:

- `b.png`
- `cloud.png`
- `loon.png`

It would be great of you could add them. This is a lovely pygame example!

**Comment by stardev24** [comment]
ya I was trying to add them but its giving some errors.Do we need to follow any specific sprite format?

**Comment by bittner** [comment]
What I did to make the errors go away is copy the `bullet.png` file to `b.png`, `cloud.png` and `loon.png`.

This makes the shooter game work, but clearly the cloud then looks like a big bullet, same for the "loon" bomb. The original assets are missing. They need to be provided by @Mariii123, I guess.

P.S.: The `bullet.png` file is referenced no-where in the source code. I would guess the `"b.png"` file may simply be renamed to `"bullet.png"` on both [line 84](https://github.com/Mariii123/heli-shooter/blob/master/heli_shooter.py#L84) and [138](https://github.com/Mariii123/heli-shooter/blob/master/heli_shooter.py#L138).

**Comment by Marishwaran99** [comment]
i added

**Comment by Marishwaran99** [comment]
please convert all files bullet image to alpha so that it will be transparent like other sprites
sorry i am not able to convert bullet image so please try and if possible send me that image

**Comment by bittner** [comment]
What is the difference between [b.png](https://github.com/Mariii123/heli-shooter/blob/master/b.png) and [bullet.png](https://github.com/Mariii123/heli-shooter/blob/master/bullet.png)? The file size is different, but the images look the same.

`bullet.png` is not referenced in the source code at all. If they are the same I would suggest to use `bullet.png` in the source code and delete the `b.png` file. This would be most self-explanatory.

**Comment by Marishwaran99** [comment]
It was stored by mistakely

**Comment by bittner** [comment]
Wow! Now that there is a startship and a black helicopter the game is even more exciting!

I'll make the code a bit more beautiful, if you don't mind, and remove the `b.png` file. You will be able to see the changes in PR #4, and merge it into your code base by clicking on the "Merge" button.

I guess this issue can then be closed.

**Comment by bittner** [comment]
I noticed that you deleted and re-uploaded the `cloud.png` and `b.png` files. Note that deleting them first is not necessary: It's fine to just "overwrite" them (in a new commit).

You still have _two_ duplicate files with different names in the repository now: `b.png` and `bullet.png`
I think you should rename the `b.png` file to `bullet.png` (hence "deleting" the `b.png` the right way).
